# Copyright (c) 2021 ICHIRO ITS
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

name: Deploy Debian Nightly
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  deploy-debian-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: musen

      - name: Build nightly Debian package
        uses: ichiro-its/ros2-build-debian-action@main
        with:
          unique-version: true

      - name: Deploy nightly Debian package to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          source: "package/*.deb"
          target: "~/temp/nightly/musen/"
          rm: true

      - name: Prepare nightly Debian package in the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ~/repository/debian
            reprepro includedeb nightly ~/temp/nightly/musen/package/*.deb
            rm -rf ~/temp/nightly/musen/
